import {
  heroBriefcaseMicro,
  heroClockMicro,
  heroEnvelopeMicro,
  heroGlobeAltMicro,
  heroHomeMicro,
  heroMapPinMicro,
  heroPhoneMicro,
  heroUserCircleMicro,
} from '@ng-icons/heroicons/micro';
import { Column } from '../types/column';
import { Person } from '../types/person';

export const COLUMNS: Array<Column<Person>> = [
  {
    key: 'avatarUrl',
    label: 'Avatar',
    icon: heroUserCircleMicro,
    sortable: false,
    resizable: false,
    defaultWidth: 100,
  },
  {
    key: 'firstName',
    label: 'First Name',
    icon: heroUserCircleMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 150,
  },
  {
    key: 'lastName',
    label: 'Last Name',
    icon: heroUserCircleMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 150,
  },
  {
    key: 'jobTitle',
    label: 'Job Title',
    icon: heroBriefcaseMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 250,
  },
  {
    key: 'company',
    label: 'Company',
    icon: heroHomeMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 200,
  },
  {
    key: 'website',
    label: 'Website',
    icon: heroGlobeAltMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 200,
  },
  {
    key: 'email',
    label: 'Email',
    icon: heroEnvelopeMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 300,
  },
  {
    key: 'phone',
    label: 'Phone',
    icon: heroPhoneMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 150,
  },
  {
    key: 'street',
    label: 'Street',
    icon: heroMapPinMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 250,
  },
  {
    key: 'city',
    label: 'City',
    icon: heroMapPinMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 200,
  },
  {
    key: 'zip',
    label: 'ZIP Code',
    icon: heroMapPinMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 150,
  },
  {
    key: 'country',
    label: 'Country',
    icon: heroMapPinMicro,
    sortable: true,
    resizable: true,
    defaultWidth: 150,
  },
  {
    key: 'createdAt',
    label: 'Created At',
    icon: heroClockMicro,
    sortable: true,
    resizable: false,
    defaultWidth: 150,
  },
  {
    key: 'updatedAt',
    label: 'Updated At',
    icon: heroClockMicro,
    sortable: true,
    resizable: false,
    defaultWidth: 150,
  },
];
